---
version: "2"
plugins:
  duplication:
    enabled: true
    exclude_paths:
    - spec/
checks:
  method-complexity:
    enabled: false
  argument-count:
    config:
      threshold: 5
exclude_patterns:
- spec/
- examples/
