language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head

sudo: required

dist: trusty

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; chmod +x ./cc-test-reporter; ./cc-test-reporter before-build; fi

before_install:
  - sudo apt-get install -qq --force-yes gcc-multilib g++-multilib
  - gem update --system
  - gem install bundler
  - gem --version

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
